USE f1_website;

INSERT INTO pilots(first_name, last_name) VALUES("Lewis", "Hamilton");
INSERT INTO pilots(first_name, last_name) VALUES("Valtteri", "Bottas");
INSERT INTO pilots(first_name, last_name) VALUES("Max", "Verstappen");
INSERT INTO pilots(first_name, last_name) VALUES("Charles", "Leclerc");
INSERT INTO pilots(first_name, last_name) VALUES("Sebastian", "Vettel");
INSERT INTO pilots(first_name, last_name) VALUES("Carlos", "Sainz Jr");
INSERT INTO pilots(first_name, last_name) VALUES("Pierre", "Gasly");
INSERT INTO pilots(first_name, last_name) VALUES("Alexander", "Albon");
INSERT INTO pilots(first_name, last_name) VALUES("Daniel", "Ricciardo");
INSERT INTO pilots(first_name, last_name) VALUES("Sergio", "Perez");
INSERT INTO pilots(first_name, last_name) VALUES("Lando", "Norris");
INSERT INTO pilots(first_name, last_name) VALUES("Kimi", "Raikkonen");
INSERT INTO pilots(first_name, last_name) VALUES("Daniil", "Kvyat");
INSERT INTO pilots(first_name, last_name) VALUES("Nico", "Hulkennberg");
INSERT INTO pilots(first_name, last_name) VALUES("Lance", "Stroll");
INSERT INTO pilots(first_name, last_name) VALUES("Kevin", "Magnussen");
INSERT INTO pilots(first_name, last_name) VALUES("Antonio", "Giovinazzi");
INSERT INTO pilots(first_name, last_name) VALUES("Romain", "Grosjean");
INSERT INTO pilots(first_name, last_name) VALUES("Robert", "Kubica");
INSERT INTO pilots(first_name, last_name) VALUES("Georges", "Russel");

INSERT INTO tracks(country) VALUES("Australie");
INSERT INTO tracks(country) VALUES("Bahrein");
INSERT INTO tracks(country) VALUES("Chine");
INSERT INTO tracks(country) VALUES("Azerbaidjan");
INSERT INTO tracks(country) VALUES("Espagne");
INSERT INTO tracks(country) VALUES("Monaco");
INSERT INTO tracks(country) VALUES("Canada");
INSERT INTO tracks(country) VALUES("France");
INSERT INTO tracks(country) VALUES("Autriche");
INSERT INTO tracks(country) VALUES("Grande-Bretagne");
INSERT INTO tracks(country) VALUES("Allemagne");
INSERT INTO tracks(country) VALUES("Hongrie");
INSERT INTO tracks(country) VALUES("Belgique");
INSERT INTO tracks(country) VALUES("Italie");
INSERT INTO tracks(country) VALUES("Singapour");
INSERT INTO tracks(country) VALUES("Russie");
INSERT INTO tracks(country) VALUES("Japon");
INSERT INTO tracks(country) VALUES("Mexique");
INSERT INTO tracks(country) VALUES("USA");
INSERT INTO tracks(country) VALUES("Bresil");
INSERT INTO tracks(country) VALUES("EAU");
